### ISSUE TITLE
Requirements.txt missing?

### ISSUE THREAD

**Issue by joeybab3** [slinger360/NineRiFt-kivy#7]
I searched this repo for "requirements.txt" to install the requirements and while I was able to find an old version it appears it is no longer in this repo?

**Comment by HelaFaye** [comment]
Packaging? https://github.com/slinger360/NineRiFt-Lite/blob/master/packaging/requirements.txt

**Comment by HelaFaye** [comment]
Next time, use the search function

**Comment by joeybab3** [comment]
Thanks, I used the search function as stated in my issue, I'm not sure why it only pulled a previous version and didn't show the current one in packaging.
